### ISSUE TITLE
Improve handling of pg_stat_statements handling of bind "IN" variables

### ISSUE THREAD

**Issue by dutow** [percona/pg_stat_monitor#406]
Improve handling of pg_stat_statements handling of bind "IN" variables

http://www.postgresql.org/message-id/CAM3SWZSpdPB3uErnXWMt3q74y0r+84ZsOt2U3HKKes_V7O+0Qg@mail.gmail.com

https://jira.percona.com/browse/PG-468

**Comment by ImTheKai** [comment]
As we move our tracking to Jira, this issue will be tracked here https://perconadev.atlassian.net/browse/PG-468
