### ISSUE TITLE
Verify correctness of timings without network overhead

### ISSUE THREAD

**Issue by dutow** [percona/pg_stat_monitor#407]
Though in our regression we are testing the timings gathered by PGSM in form of aggregation, min, max, total and making sure these are not null.

Peter is not sure about the correctness of timings gathered by PGSM where network overhead is not part of the gathered timings.

Need to increase the scope of testing to make sure that not only this concern is addressed as part of regression or testing.

For reference, this was discussed under this [document/feedback](https://docs.google.com/document/d/1ybHREpYw8PIc4Fqz8iQqu5xdu6K2xjvdF_j8i1mugVg/edit?disco=AAAAiXJEgfE) from Peter.

https://jira.percona.com/browse/PG-535

**Comment by Naeem-Akhter** [comment]
@EngineeredVirus is this that could be implemented within the scope of PGSM regression? Your input?

**Comment by ImTheKai** [comment]
Issue will be tracked here https://perconadev.atlassian.net/browse/PG-535
