### ISSUE TITLE
pg_stat_monitor: PostgreSQL 15's pg_stat_statements new fetures support

### ISSUE THREAD

**Issue by dutow** [percona/pg_stat_monitor#408]
Here is the list of new features added in PostgreSQL - 15. We need to add the support of these functionalities into pg_stat_monitor. 

1. Allow [pg_stat_reset_single_table_counters()](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-STATS-FUNCS-TABLE) to reset the counters of relations shared across all databases.
2. Add system view [pg_stat_subscription_stats](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-SUBSCRIPTION-STATS) to report on subscriber activity.
3. Add counters for temporary file block I/O to [pg_stat_statements](https://www.postgresql.org/docs/current/pgstatstatements.html).
4. Add JIT counters to pg_stat_statements.
6. A few new columns were added in pg_stat_statments.
  * jit_functions
  * jit_generation_time
  *  jit_inlining_count
  *  jit_inlining_time
  *  jit_optimization_count
  *  jit_optimization_time
  *  jit_emission_count
  *  jit_emission_time

https://jira.percona.com/browse/PG-540

**Comment by artemgavrilov** [comment]
All new fields were added, but items 1 and 2 are not

**Comment by ImTheKai** [comment]
Will be tracked here moving forward https://perconadev.atlassian.net/browse/PG-540
