### ISSUE TITLE
Sometimes the sys or user timings come as 0

### ISSUE THREAD

**Issue by dutow** [percona/pg_stat_monitor#411]
Even in cases with hundreds of executions, the user or sys time being zero is not correct. Therefore, this needs more review. This could be an issue any because of poor handling of query nesting.

It seems, due to same problem, for INSERT queries at times PGSM shows (cpu_sys_time + cpu_user_time > total_exec_time)

https://jira.percona.com/browse/PG-612

**Comment by ImTheKai** [comment]
Will be tracked here https://jira.percona.com/browse/PG-612
