### ISSUE TITLE
Need a view definition which produces pg_stat_statements compatible view

### ISSUE THREAD

**Issue by jobinau** [percona/pg_stat_monitor#431]
A large number of PostgreSQL users / DBAs have tools and scripts prepared for `pg_stat_statements`.
The lack of `pg_stat_statement` compatible view definition stands as the biggest obstacle for replacing the `pg_stat_statements` with `pg_stat_monitor`
A standard view definition is documentation that could enable users to make the easy switches and thereby accelerate the adoption of `pg_stat_monitor`

**Comment by EngineeredVirus** [comment]
We should add a GUC, perhaps named "enable_pgss_compability". When enabled, it should create a "pg_stat_statements" compatible view with "CREATE EXTENSION". By default, this GUC should be set. There should be a separate SQL function that can create this compatible view later on.

**Comment by ImTheKai** [comment]
Will be tracked https://perconadev.atlassian.net/browse/PG-809
