### ISSUE TITLE
Make pg_stat_monitor ready for PostgreSQL 17

### ISSUE THREAD

**Issue by ImTheKai** [percona/pg_stat_monitor#454]
### Description

PostgreSQL 17 will be released by the end of Q3, this year. As such we need to ensure, that pg_stat_monitor works with it, before the upstream release happens. This is also crucial, as upstream has their build pipelines as well. , we need to make sure

### Suggested solution

Make pg_stat_monitor work with PostgreSQL 17.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artemgavrilov** [comment]
According to https://www.postgresql.org/developer/beta/ first PG 17 beta will be available in May 2024.

**Comment by artemgavrilov** [comment]
Ticket for updating PMM Dashborads: https://perconadev.atlassian.net/browse/PMM-13154

**Comment by ImTheKai** [comment]
Will be tracked here - https://perconadev.atlassian.net/browse/PG-810
