### ISSUE TITLE
Use DSM registry

### ISSUE THREAD

**Issue by artemgavrilov** [percona/pg_stat_monitor#467]
### Description

PG 17 introduces Dynamic Shared Memory registry that allows to use shared memory without configuring `shared_preload_libraries` (i.e. enable extension without PG restart). We should support this feature.

https://github.com/postgres/postgres/commit/8b2bcf3f
https://commitfest.postgresql.org/46/4684/

### Additional context

Related to https://github.com/percona/pg_stat_monitor/issues/454

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ImTheKai** [comment]
Will be tracked here - https://perconadev.atlassian.net/browse/PG-811
