### ISSUE TITLE
0.6.0 build failure

### ISSUE THREAD

**Issue by devrimgunduz** [percona/pg_stat_monitor#59]
Hi,

0.6.0 fails to build against GCC 9 and 10. Can you please take a look?

Thanks! Devrim

`gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -shared -o pg_stat_monitor.so hash_query.o guc.o pg_stat_monitor.o  -L/usr/pgsql-12/lib   -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-12/lib',--enable-new-dtags -lm   
/usr/bin/ld: guc.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:328: multiple definition of `conf'; hash_query.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:328: first defined here
/usr/bin/ld: guc.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:302: multiple definition of `prev_shmem_startup_hook'; hash_query.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:302: first defined here
/usr/bin/ld: guc.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:255: multiple definition of `pgss_qbuf'; hash_query.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:255: first defined here
/usr/bin/ld: pg_stat_monitor.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:255: multiple definition of `pgss_qbuf'; hash_query.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:255: first defined here
/usr/bin/ld: pg_stat_monitor.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:328: multiple definition of `conf'; hash_query.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:328: first defined here
/usr/bin/ld: pg_stat_monitor.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:302: multiple definition of `prev_shmem_startup_hook'; hash_query.o:/build/main/pg_stat_monitor-0.6.0/pg_stat_monitor.h:302: first defined here
collect2: error: ld returned 1 exit status
`

**Comment by ibrarahmad** [comment]
Hi Devrim, 

It works on ubuntu gcc version 9. I will check that on redhat.

vagrant@vagrant:~/pg_stat_monitor$ gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE   -c -o hash_query.o hash_query.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE   -c -o guc.o guc.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE   -c -o pg_stat_monitor.o pg_stat_monitor.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -shared -o pg_stat_monitor.so hash_query.o guc.o pg_stat_monitor.o  -L/usr/local/pgsql/lib    -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags -lm

**Comment by devrimgunduz** [comment]
Thanks @ibrarahmad

**Comment by EvgeniyPatlan** [comment]
Hi @devrimgunduz 
I have checked this issue on centos system too.
By default Centos8 has gcc-8(which is latest for Centos systems) - so with gcc-8 everything works well.
Also it is possible to install gcc-9 using gcc-toolset
I successfully installed gcc-9 on Centos8, added all needed dependencies and successfully built pg_stat_monitor.

**Comment by ibrarahmad** [comment]
@devrimgunduz Issue is fixed. The issue is only reproduced when compiled -fno-common.

**Comment by devrimgunduz** [comment]
@ibrarahmad thanks! I'll build the RPMs when you release a new tarball.
